/*
 * Default page layout.
 * This file is automatically generated by generate_js.py
 */

export const PAGE_LAYOUT = (
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data[:old_pos + 1] +  +
     + data + 
);
