"""
Generate font data.
"""

import os

def generate_page_layout():
    pass

def generate_font():
    FONT_FILE = os.path.join(os.path.dirname(__file__), "newstroke.woff2");
    JS_FILE = os.path.join(os.path.dirname(__file__), "ki_font.js");

    with open(FONT_FILE, "rb") as font_file:
        font_data = font_file.read()

    # Format the font data to a string with line breaks every 80 characters
    font_data = ", ".join(map(str, list(font_data)))
    output = "/* Font to add to the canvas.\n"
    output += " * Font: Newstroke (https://www.onlinewebfonts.com/download/e2394cb7d30696bdf001b6028851e91a)\n"
    output += " * This file is automatically generated by generate_font_js.py\n"
    output += " */\n\n"
    output += "export function loadFont()\n"
    output += "{\n"
    output += "    const font = new FontFace('KiCadFont', KI_FONT.buffer);\n"
    output += "    font.load().then(function(loadedFont) {\n"
    output += "        document.fonts.add(loadedFont);\n"
    output += "    });\n"
    output += "}\n\n"
    output += "const KI_FONT = new Uint8Array([\n"
    max_line_length = 94
    pos = 1
    while pos > 0:
        pos = font_data.find(", ", max_line_length - 3)
        if pos > 0:
            output += "    " + font_data[:pos] + ",\n"
            font_data = font_data[pos + 2:]
    if len(font_data) > 0:
        output += "    " + font_data + "\n"
    output += "]);\n"

    with open(JS_FILE, "w") as js_file:
        js_file.write(output)


if __name__ == "__main__":

    generate_page_layout()
    generate_font()
