"""
Generate JS files with data.
"""

import os

def generate_page_layout():
    SRC_FILE = os.path.join(os.path.dirname(__file__), "artifacts", "pagelayout.kicad_wks");
    JS_FILE = os.path.join(os.path.dirname(__file__), "ki_pagelayout.js");

    with open(SRC_FILE, "r") as font_file:
        data = font_file.read()

    # Remove tabs and replace line endings with space
    data = data.replace('\t', '').replace('\r', '').replace('\n', ' ').replace(' )', ')').strip()
    output = "/* Default page layout.\n"
    output += " * This file is automatically generated by generate_js.py\n"
    output += " */\n\n"
    output += "export const pageLayout = (\n";
    max_line_length = 92
    pos = 0
    old_pos = 0
    while pos < len(data):
        if data[pos] == ')':
            old_pos = pos
        if pos > max_line_length:
            output += "    '" + data[:old_pos + 1] + "' +\n"
            data = data[old_pos + 1:]
            pos = 0
            old_pos = 0
        pos += 1
    if len(data) > 0:
        output += "    '" + data + "'\n"
    output += ");\n"

    with open(JS_FILE, "w") as js_file:
        js_file.write(output)


def generate_font():
    SRC_FILE = os.path.join(os.path.dirname(__file__), "artifacts", "newstroke.woff2");
    JS_FILE = os.path.join(os.path.dirname(__file__), "ki_font.js");

    with open(SRC_FILE, "rb") as font_file:
        data = font_file.read()

    # Format the font data to a string with line breaks every 80 characters
    data = ", ".join(map(str, list(data)))
    output = "/* Font to add to the canvas.\n"
    output += " * Font: Newstroke (https://www.onlinewebfonts.com/download/e2394cb7d30696bdf001b6028851e91a)\n"
    output += " * This file is automatically generated by generate_js.py\n"
    output += " */\n\n"
    output += "export function loadFont()\n"
    output += "{\n"
    output += "    const font = new FontFace('KiCadFont', KI_FONT.buffer);\n"
    output += "    font.load().then(function(loadedFont) {\n"
    output += "        document.fonts.add(loadedFont);\n"
    output += "    });\n"
    output += "}\n\n"
    output += "const KI_FONT = new Uint8Array([\n"
    max_line_length = 94
    pos = 1
    while pos > 0:
        pos = data.find(", ", max_line_length - 3)
        if pos > 0:
            output += "    " + data[:pos] + ",\n"
            data = data[pos + 2:]
    if len(data) > 0:
        output += "    " + data + "\n"
    output += "]);\n"

    with open(JS_FILE, "w") as js_file:
        js_file.write(output)


if __name__ == "__main__":

    generate_page_layout()
    generate_font()
